### ISSUE TITLE
Use metaphlan output as input for this tool

### ISSUE THREAD

**Issue by PulkitLeuva** [danielchang2002/GMWI2#1]
Hello, I have generated metaphlan output files for my samples. I want to use that output as input for this tool. Can I do it? and how?

**Comment by JiatingH** [comment]
I also have the same need which can save a lot of time. Could developers make it accept more files from previous metaphlan analysis?

**Comment by danielchang2002** [comment]
@PulkitLeuva @JiatingH Thanks for this suggestion. Will work on adding this option!

**Comment by Jtrachsel** [comment]
+1 for the ability to just provide a metaphlan profile.  This feature would be extremely useful.

**Comment by danielchang2002** [comment]
@PulkitLeuva @JiatingH @Jtrachsel Just added a script for scoring metaphlan profiles (check README), it should run smoothly if you have all the dependencies installed w/ the tool!

**Comment by jun-yeong-heo** [comment]
Many thanks. It's simple, quick and works perfectly.
If anyone gets an error while using metaphlan4, just add an "UNKNOWN\t-1\t0" row above "k__Bacteria" in the metaphlan result file and change `skiprows=3` to `skiprows=4` in the 14th line of the python code. Everything will be fine.

**Comment by danielchang2002** [comment]
Thanks @jun-yeong-heo. Although, for computing the GMWI2 scores, I recommend you use MetaPhlAn3 with the marker database we used. Because there are many minor name changes of taxa between versions, using MetaPhlAn4 instead of MetaPhlAn3 will mess up the scoring!
